project_id = "xrkefhwtboyezavumlle"

[functions.create-demo-users]
verify_jwt = true

[functions.send-request-notification]
verify_jwt = true

[functions.send-device-issued-notification]
verify_jwt = true

[functions.send-signup-notification]
verify_jwt = false

[functions.site-chatbot]
verify_jwt = false

[functions.totp-manage]
verify_jwt = false

[functions.security-check]
verify_jwt = false
