project_id = "xrkefhwtboyezavumlle"

[functions.create-demo-users]
verify_jwt = true

[functions.send-request-notification]
verify_jwt = true

[functions.send-device-issued-notification]
verify_jwt = true
